### ISSUE TITLE
求拉群，二维码已过期

### ISSUE THREAD

**Issue by GuanFoxyier** [SeeFlowerX/stackplz#2]
求拉群，二维码已过期

**Comment by SeeFlowerX** [comment]
请从star列表查找熟悉的人进行邀请，如果他们已经加入了群

**Comment by rogxo** [comment]
求拉群

**Comment by SeeFlowerX** [comment]
更新了二维码 https://github.com/SeeFlowerX/stackplz/blob/dev/images/Snipaste_2023-05-19_21-57-39.png

**Comment by Ainevsia** [comment]
求拉群，先谢谢了

**Comment by JiaHuann** [comment]
你好，求拉群，谢谢！

**Comment by SeeFlowerX** [comment]
ping https://github.com/SeeFlowerX/stackplz/releases/tag/v2.0.0_beta2
