### ISSUE TITLE
能否追踪内核任意函数?

### ISSUE THREAD

**Issue by chillsoul** [SeeFlowerX/stackplz#27]
能否做到 类似于bcc的trace工具，追踪vfs read中的信息（inode、offset、len）？
测试了stackplz可以追踪read write syscall，但是这些系统调用只能获取到fd，没办法获取到inode这些需要用到的信息。

**Comment by chillsoul** [comment]
另外交流群二维码过期了 有新的吗？

**Comment by SeeFlowerX** [comment]
1. readme二维码更新了
2. 不支持跟踪任意内核函数，其他工具也许可以，没精力实现那些
3. 可以自行搭建bcc的环境，在手机上使用bcc，比如[eadb](https://github.com/tiann/eadb)
