### ISSUE TITLE
android12下无法使用

### ISSUE THREAD

**Issue by yxbbing123** [SeeFlowerX/stackplz#3]
/stackplz stack --prepare   
< 2022/12/08 01:44:44 Kernel config read failed, error:Config disabled, item :CONFIG_UPROBES.

 # uname -r
4.9.270-g862f51bac900-ab7613625
是内核不够版版吗？

**Comment by yxbbing123** [comment]
uname -r
4.9.270-g862f51bac900-ab7613625  
内核是4.9.27

**Comment by yxbbing123** [comment]
blueline:/data/local/tmp # uname -a
Linux localhost 4.9.270-g862f51bac900-ab7613625 #0 SMP PREEMPT Thu Aug 5 07:04:42 UTC 2021 aarch64

**Comment by SeeFlowerX** [comment]
**你好，4.9比4.14小**
