### ISSUE TITLE
想了解下这个模块怎么实现的硬件断点?

### ISSUE THREAD

**Issue by zbx911** [SeeFlowerX/stackplz#31]
!!

**Comment by zbx911** [comment]
ebpf自带，还是直接调用内核的api

**Comment by SeeFlowerX** [comment]
具体实现在这个地方，用的perf实现的，严格来说不是ebpf的功能。

https://github.com/SeeFlowerX/ebpf/blob/bbb7a6709c3d79106fb94421577e45246c10aa3a/perf/ring.go#L128
