### ISSUE TITLE
[FR] 调用命令行启动并监控进程

### ISSUE THREAD

**Issue by Ylarod** [SeeFlowerX/stackplz#32]
比如分析 native 进程的时候：
```
as option:

./stackplz -s all --exec "./foo" 

or

as parameter:

./stackplz -s all -- "./foo" 
```

**Comment by SeeFlowerX** [comment]
可执行程序在另一个shell正常运行即可，先通过`echo $$`获取到pid，然后用`--no-pid`排除掉即可

```bash
./stackplz -s all --pid {pid} --no-pid {pid}
```

**Comment by Ylarod** [comment]
> 可执行程序在另一个shell正常运行即可，先通过`echo $$`获取到pid，然后用`--no-pid`排除掉即可
> 
> ```shell
> ./stackplz -s all --pid {pid} --no-pid {pid}
> ```

这样追踪不到启动时的 syscall，实现的时候可以 fork -> 记录并追踪子进程PID -> 子进程exec

**Comment by SeeFlowerX** [comment]
那可以在执行可执行程序的时候，再套一个shell，比如`/system/bin/sh ./foo`

**Comment by SeeFlowerX** [comment]
或者不套也行，就追踪运行可执行程序的那个shell的全部syscall也是一样，也不会有多少干扰

**Comment by Ylarod** [comment]
1. shell 1
```sh
echo $$
```

2. shell 2
```sh
stackplz -p pid
```

3. shell 1
```sh
./foo
```
