### ISSUE TITLE
[FR] 快速发送SIGCONT

### ISSUE THREAD

**Issue by Ylarod** [SeeFlowerX/stackplz#33]
当使用 --kill SIGSTOP 的时候，直接在 CLI 里面 回车就发送 SIGCONT，让对应进程继续运行

**Comment by SeeFlowerX** [comment]
已实现，按`c + Enter`让有记录的进程恢复运行；单独回车用来增加已有日志空白比较多，还是按c吧（

https://github.com/SeeFlowerX/stackplz/commit/1cb51b8eb59a8e58fd4dd0290ec06f1d6627d1f7
