### ISSUE TITLE
[FR] 回溯堆栈时打印原始PC值

### ISSUE THREAD

**Issue by Ylarod** [SeeFlowerX/stackplz#34]
有些加固后的 so 可能显示的是基于`[anon:.bss]` 的偏移，但是这种有多个，无法确定具体是哪个，可以加一个选项打印原始PC值

**Comment by SeeFlowerX** [comment]
加上`--mstack`是会打印原始pc值的，翻了下libunwindstack的代码好像没有提供打印原始pc的设定，除非是unknown。可以用`--mstack`应付下...，`--mstack`和`--stack`是一起使用的。

https://aosp.app/android-12.1.0_r1/xref/system/unwinding/libunwindstack/Unwinder.cpp#327

**Comment by SeeFlowerX** [comment]
后面看看加上吧，这个可以自行控制输出形式。

https://github.com/wangshengyang1996/CrashCatcher/blob/3d7cc5314c8b54e4528b7a676e769e07b3fcd19c/crashdumper/src/main/cpp/stack_tracer.cpp#L61

**Comment by SeeFlowerX** [comment]
已实现，添加`--showpc`选项即可，使用该选项时输出形式如下：

> #00 pc 0000006ed450c898 0000000000133898  [anon:.bss]

https://github.com/SeeFlowerX/stackplz/commit/2f909747538400c5f198c74e238c7655629d44ef
https://github.com/SeeFlowerX/unwinddaemon/commit/1274ef46a138b7db7ea588700a7cbc63e41ce761
