### ISSUE TITLE
这边实现对libc strstr函数的hook是怎么做到的呀?

### ISSUE THREAD

**Issue by Gavin0210** [SeeFlowerX/stackplz#39]
能指路个关键代码入口吗?

**Comment by SeeFlowerX** [comment]
核心函数在read_args

- https://github.com/SeeFlowerX/stackplz/blob/563fd9d849eec50e51f221cbbfd30f99a519ec7a/src/stack.c#L77
- https://github.com/SeeFlowerX/stackplz/blob/563fd9d849eec50e51f221cbbfd30f99a519ec7a/src/utils.h#L29
