### ISSUE TITLE
Android T 部分系统进程及系统 APP 无法 Hook

### ISSUE THREAD

**Issue by framework-bug-maker** [SeeFlowerX/stackplz#4]
大佬好，我在 Android T 版本的 Pixel 4 上使用 stackplz 后发现部分系统进程及系统 APP 无法 Hook

./stackplz --name com.android.systemui syscall --nr 63 --regs --stack
Error: not support package=com.android.systemui primaryCpuAbi=null
./stackplz --name android syscall --nr 63 --regs --stack
Error: not support package=android primaryCpuAbi=null

能否像 uprobe_events 那样不用必须指定 name 或 uid，直接指定 so 的路径即可 hook 呢？

这样就方便 hook surfaceflinger 等没有在 dumpsys package 里的进程了。

**Comment by SeeFlowerX** [comment]
我测试v1.9.0这个版本，使用你的命令是可以对`com.android.systemui`进行hook的，难道Android T的dumpsys没有primaryCpuAbi了吗？

https://github.com/SeeFlowerX/stackplz/releases/tag/v1.9.0

![image](https://user-images.githubusercontent.com/70688581/221452306-1760cdae-644f-495f-91e6-a327c84db764.png)


---

请你测试下这个命令的输出

```bash
dumpsys package com.android.systemui | grep -i arm
```

---

另外没有发现手机有名为`android`的系统进程（通过ps -ef命令），我记得是app_process命令行直接运行apk？类似于scrcpy这种好像是会默认是这个名字

---

不指定name和uid当然是可以的，但是对于本项目来说存在一些问题：

1. 项目本身是针对普通APP进行追踪的
2. 系统进程往往调用过多，本项目的效果很差，会大量出现数据丢失的情况；这样其实也拿不到什么有意义的数据

你要hook surfaceflinger，建议使用bcc编写脚本，通过pid去hook

**Comment by framework-bug-maker** [comment]
刚试了下，在 T 版本 Redmi K50 Ultra 上 primaryCpuAbi 正常，但在我自己打包刷机的 AOSP T 版本 Pixel 4 primaryCpuAbi  为 null，原因还在调查中。

```
flame:/ # dumpsys package com.android.systemui | grep -C 10 "Package \[com.android.systemui\]"
      applicationInfo=ApplicationInfo{4a628e1 com.android.systemui}
  [com.android.systemui.keyguard]:
    Provider{7d88ae0 com.android.systemui/.keyguard.KeyguardSliceProvider}
      applicationInfo=ApplicationInfo{a3a2606 com.android.systemui}

Key Set Manager:
  [com.android.systemui]
      Signing KeySets: 2

Packages:
  Package [com.android.systemui] (1f65568):
    userId=10086
    sharedUser=SharedUserSetting{255ad2a android.uid.systemui/10086}
    pkg=Package{1b9b71b com.android.systemui}
    codePath=/system_ext/priv-app/SystemUI
    resourcePath=/system_ext/priv-app/SystemUI
    legacyNativeLibraryDir=/system_ext/priv-app/SystemUI/lib
    extractNativeLibs=false
    primaryCpuAbi=null
    secondaryCpuAbi=null
    cpuAbiOverride=null
```

dumpsys package 里的 android 应该是指 system_server

```
flame:/ # dumpsys package android | grep -C 10 "Package \[android\]"
ContentProvider Authorities:
  [com.android.textclassifier.icons]:
    Provider{4a68a22 android/com.android.server.textclassifier.IconsContentProvider}
      applicationInfo=ApplicationInfo{85b22db android}

Key Set Manager:
  [android]
      Signing KeySets: 2

Packages:
  Package [android] (d0c3a0a):
    userId=1000
    sharedUser=SharedUserSetting{bc9fd86 android.uid.system/1000}
    pkg=Package{37494e8 android}
    codePath=/system/framework/framework-res.apk
    resourcePath=/system/framework/framework-res.apk
    legacyNativeLibraryDir=/system/lib64/framework-res
    extractNativeLibs=false
    primaryCpuAbi=null
    secondaryCpuAbi=null
    cpuAbiOverride=null
```

如果能跟踪系统进程的话，对于学习 Android 系统可能比较有帮助，我看看后面能不能改个版本。

谢大佬回复。
