### ISSUE TITLE
Is replace filter deprecated?

### ISSUE THREAD

**Issue by mrmischi3f** [SeeFlowerX/stackplz#43]
Based on this [post](https://blog.seeflower.dev/archives/269/) you can set a filter starting with 'r:' that will replace the argument for another one of your choice (specified with `:::`)

This filter seems not to be valid anymore but I am really interested on it. Is there any workaround that I could do to have the same effect? Can you help me?

**Comment by SeeFlowerX** [comment]
This feature exist between v2.0.8-v2.1.4, deprecated after v2.1.4

bpf_probe_write_user does not always work right, so I have not implement it after v2.1.4.
