### ISSUE TITLE
mac m1 ubuntu redroid下，pid和tid一直为0

### ISSUE THREAD

**Issue by ltlly** [SeeFlowerX/stackplz#44]
macbookAir m1 pd ubuntu22.04  全新拉取镜像 redroid/redroid:14.0.0_64only-latest  13 12 下 hook任意apk 任意点 均有此问题，

在默认的5.15.0-76-generic内核下

使用 ./stackplz --nocheck -n com.chinarainbow.tft -s %file   时 显示的pid和tid为0

在自己编译的6.5.8内核（仅多开启了/proc/config,gz相关的功能）中， 

使用./stackplz  -n com.chinarainbow.tft -s %file    时pid和tid也为0

有时候pid会为极大值（没截到图

![image](https://github.com/SeeFlowerX/stackplz/assets/86669384/cff631eb-cda1-40fe-a012-4e6953c15593)

ps -ef回显正常
![image](https://github.com/SeeFlowerX/stackplz/assets/86669384/3472e5e7-46b0-484f-9748-c6822dd50dd2)

但在orangepi5b上的redroid获取pid和tid正常显示，5b的cuttlefish下也正常工作

**Comment by SeeFlowerX** [comment]
加上`--btf`选项试试

**Comment by ltlly** [comment]
加上--btf选项后工作正常  即使用  ./stackplz --nocheck --btf -n com.chinarainbow.tft -s %file
