### ISSUE TITLE
--stack堆栈回溯出现Segmentation fault

### ISSUE THREAD

**Issue by oneSeeker279** [SeeFlowerX/stackplz#48]
云真机,https://aochenyun.com/index.html
这个云真机官方采用的是rk3588开发板
内核是5.10.110-2.6.2.lxc,
其他功能都能正常使用，
但是一加上--stack命令进行堆栈回溯时便会出现Segmentation fault,从2.1.4到最新版都是出现Segmentation fault
这是libunwindstack.so这个库与这个云真机不匹配的原因么
输入:
./stackplz -n mark.via --syscall sendto --dumphex --stack
输出:
uid => whitelist:[10101];blacklist:[]
pid => whitelist:[29842];blacklist:[]
tid => whitelist:[];blacklist:[]
start 2 modules
Segmentation fault

**Comment by SeeFlowerX** [comment]
试一下手动删除preload_libs目录，然后再试试；另外你可以在logcat找一下具体的报错是什么

- https://github.com/SeeFlowerX/stackplz/releases/tag/v3.0.3

**Comment by SeeFlowerX** [comment]
我看了下这个网站，可能是因为它系统是安卓10的原因。需要安卓12起的系统。

**Comment by oneSeeker279** [comment]
明白了，谢谢老哥，今天看Release里面发现V3.0.0有一条是“修复了某些云手机上数据读取异常的情况”，
方便请教下老哥老哥这个提到的是哪个云手机平台么，我想再测试一下，拜谢😊

**Comment by SeeFlowerX** [comment]
https://github.com/SeeFlowerX/stackplz/issues/42

这个实际上是他自己用的arm服务器，跑的redroid。

如果要在安卓10上运行，要自己拉aosp 10编译一份unwinddaemon

不过目前正在测试改进编译方式，也可以等下个星期的消息

**Comment by oneSeeker279** [comment]
好的 等待老哥的好消息 谢谢老哥的回复😁

**Comment by SeeFlowerX** [comment]
已经完成预编译库编译方式的改进，应该是可以在安卓10上正常使用了；请你测试一下

https://github.com/SeeFlowerX/stackplz/actions/runs/8336677172

**Comment by oneSeeker279** [comment]
![image](https://github.com/SeeFlowerX/stackplz/assets/88316533/7e34736d-702f-4915-9fa2-41b13a4c4729)
在这个Android10云真机上可以正常使用，谢谢老哥😁
