### ISSUE TITLE
硬件断点 读取操作 无效

### ISSUE THREAD

**Issue by junknet** [SeeFlowerX/stackplz#49]
硬件断点示例如下，支持的断点类型：r,w,rw,x
测试过程
:按照实例执行 
./stackplz --pid `pidof com.taobao.taobao` --brk 0x70ddfd63f0:r 
./stackplz --pid `pidof com.taobao.taobao` --brk 0x70ddfd63f0:rw

目标进程循环读取指定位置字节 ，使用绝对内存地址，地址为libart.so RegisterNative函数处

使用自编写apk读取也无法触发读断点

期望结果:
触发读取事件

测试结果：
未触发任何事件

测试环境：
真机pixel6 android13 lineageos系统 软件为lastest release版本

**Comment by SeeFlowerX** [comment]
RegisterNative应该下执行断点吧，你试下 x

**Comment by junknet** [comment]
> RegisterNative应该下执行断点吧，你试下 x

x 有效，
我本意是监控apk本身对这个内存地址是否有读取动作

**Comment by SeeFlowerX** [comment]
有几种情况

1. 你下断点的时机太晚
2. 你把执行到这个位置误认为在读取这个位置


关于你自己写的demo和taobao，请对着IDA确定汇编对应的指令是在读取，并给出截图等证明。
