### ISSUE TITLE
dev 分支执行命令报错

### ISSUE THREAD

**Issue by mugabutie** [SeeFlowerX/stackplz#54]
环境：Redmi Note 11T Pro  android 13   miui 14 内核为：5.10.101-android12-9-00027-g1292f517889e-ab8602202
执行命令：  ./stackplz -n ???.???.???,iso -w popen[str.f0.f1] -f r:mount:::mounx -f "r:which su:::which zz" --stack
报错内容：

findBTFAssets btf_file=a12-5.10-arm64_min.btf
hook uprobe, count:1
StackMod	module Run failed, [skip it]. error:couldn't start bootstrap manager error:1 error occurred:
	* error:opening uprobe: creating perf_uprobe PMU: token :0xe5230: opening perf event: invalid argument , isRet:false, opts:&{0 0 0 0 0  false }, {UID:, EbpfFuncName:probe_stack_0}

, probes activation validation failed .

**Comment by SeeFlowerX** [comment]
1. dev目前不存在replace功能
2. 请使用偏移方式下断，自动解析符号不可靠

**Comment by SeeFlowerX** [comment]
https://github.com/SeeFlowerX/stackplz/issues/43
