### ISSUE TITLE
内核下硬件断点会死机重启，是因为ebpf是个循环，不能加入任何延迟操作包括sleep、函数超时

### ISSUE THREAD

**Issue by zbx911** [SeeFlowerX/stackplz#56]
echo 1 > /proc/sys/kernel/kptr_restrict
cat /proc/kallsyms  | grep "T sys_"
./stackplz --brk 0xffffff93c5beb634:x --pid `pidof com.sfx.ebpf` --stack
./stackplz --brk 0xffffffc0003654dc:x --pid `pidof com.sfx.ebpf` --regs

**Comment by SeeFlowerX** [comment]
是的，此事在README中亦有说明
