### ISSUE TITLE
stackplz_arm64和--jstack找不到

### ISSUE THREAD

**Issue by LittleMango** [SeeFlowerX/stackplz#58]
hello，我看介绍可以使用--jstack，命令如下，发现是stackplz_arm64，而不是stackplz，在最新的release/3.0.3中只能下载stackplz，而通过stackplz -h查看，并没有--jstack这个flag，请问是不是要去哪里下载stackplz_arm64这个程序呢？
`./stackplz_arm64 -n com.wsy.crashcatcher -w raise --stack --jstack --showpc --kill SIGSTOP`

**Comment by LittleMango** [comment]
看了一下发布时间，看来是还没发布包含jstack的release版本 :)

**Comment by SeeFlowerX** [comment]
> 从Releases或者Github Action下载最新预编译好的二进制文件即可

https://github.com/SeeFlowerX/stackplz/actions/runs/9796822244

**Comment by LittleMango** [comment]
> > 从Releases或者Github Action下载最新预编译好的二进制文件即可
> 
> https://github.com/SeeFlowerX/stackplz/actions/runs/9796822244

搞定，很好用，这下看到vdex中具体是哪个java方法调过来的了
