### ISSUE TITLE
可否加一些过滤条件?

### ISSUE THREAD

**Issue by weststarqp** [SeeFlowerX/stackplz#6]
可能是我刚学会用,按照目前看到的教程,使用效果很不错,但log太多了,比如:./stackplz --name com.wodi.who stack --symbol strstr ,可否指定只输出来自某个so的调用,或者只输出指定--name的调用?

**Comment by SeeFlowerX** [comment]
欢迎PR

**Comment by SeeFlowerX** [comment]
目前最新版已经加入了线程名黑白名单、线程/进程号黑名单功能

以及参数读取等等，新的命令如下：

```
./stackplz -n com.xingin.xhs --point pthread_create[int,int,int,int] -o tmp.log --debug
```

至于`某个so的调用`做起来会比较有难度，不过目前加入了`--tnames thread_name`这样的方案，可以按线程名过滤了

以及你可以使用`--getoff`解析出来LR和PC是从什么so来的

如果有其他疑问，请重新打开issue
