### ISSUE TITLE
unknown filter type:r

### ISSUE THREAD

**Issue by hgy413** [SeeFlowerX/stackplz#60]
类似于`./stackplz -n com.xx.xxx -s openat:f0 -f r:/system/bin/su:::/system/bin/zz` 尝试运行会提示：
**panic: AddFilter failed, unknown filter type:r**

是不支持这样的替换吗？谢谢

**Comment by hgy413** [comment]
另外 `./stackplz -n  com.xx.xxx -s %file | grep "/sbin/su"` 也会导致卡死，如果不使用` | grep "/sbin/su"`就正常

**Comment by SeeFlowerX** [comment]
并不一定是卡死，也许是没有输出？你多按Ctrl + C几次能正常退出就不是卡死

**Comment by SeeFlowerX** [comment]
unknown filter type:r -> https://github.com/SeeFlowerX/stackplz/issues/43
