### ISSUE TITLE
断点断不到任何数据

### ISSUE THREAD

**Issue by ZYPyDoki** [SeeFlowerX/stackplz#63]
设备：红米note12turbo
内核版本：5.10.186
系统：MIUI 14.0.16
root：KernelSu

Screenshot_2024-10-23-16-09-49-958_me.weishu.kernelsu.jpg

断点始终断不到任何数据，r，w，rw，x都不可行，无论值发生怎样的变化

**Comment by SeeFlowerX** [comment]
你好好看一下你的issue，我能做任何复现吗？

**Comment by ZYPyDoki** [comment]
> 你好好看一下你的issue，我能做任何复现吗？

对不起，是我鲁莽了，请问我如果刷别的内核会可行吗？

**Comment by ZYPyDoki** [comment]
> > 你好好看一下你的issue，我能做任何复现吗？
> 
> 对不起，是我鲁莽了，请问我如果刷别的内核会可行吗？


已解决，方法：换回官方内核或者tv(vk)内核

**Comment by SeeFlowerX** [comment]
解决了就好，以防你不知道我的回复是什么意思，补一张图。

**Comment by SeeFlowerX** [comment]
![Screenshot_2024-10-26-09-21-48-486_com android chrome](https://github.com/user-attachments/assets/7c27537c-df3e-4687-a9f2-99f6ff059fd7)

**Comment by ZYPyDoki** [comment]
> ![Screenshot_2024-10-26-09-21-48-486_com android chrome](https://github.com/user-attachments/assets/7c27537c-df3e-4687-a9f2-99f6ff059fd7)
> 

这张没显示的图就是之前我刷的那个内核的ksu界面图，那个ksu是叫5.10.186微内核内置ksuroot，这张图我删了，现在已经刷了tv内核，再截图内核版本已经是5.10.168了![Screenshot_2024-10-26-09-53-55-621_me.weishu.kernelsu.jpg](https://github.com/user-attachments/assets/9655f406-8e38-4fa4-8348-6f7d2594332e)
