### ISSUE TITLE
Report：error:uid is 0, libc.so + pthread_create

### ISSUE THREAD

**Issue by JiaHuann** [SeeFlowerX/stackplz#7]
./stackplz --name com.p1.mobile.putong stack --symbol pthread_create --reg x2 -o tmp.log
stack_2023/05/31 01:42:43 StackMod      hook info:libc.so + pthread_create
stack_2023/05/31 01:42:43 StackMod      module Run failed, [skip it]. error:uid is 0, libc.so + pthread_create
stack_2023/05/31 01:42:43 No runnable modules, Exit(1)

报错如上？为什么uid为0不能用呢？

**Comment by SeeFlowerX** [comment]
因为设计问题，屏蔽了uid 0相关的处理

**Comment by JiaHuann** [comment]
所以最细的粒度只能是应用程序最上层的package吗？再往下的一些fork出来的子进程就没办法指定查看了吗？我能否不改变当前大体设计做一些patch work去细化粒度？感谢您的回答，我是安卓方面的新手，感谢赐教

**Comment by JiaHuann** [comment]
所以最细的粒度只能是应用程序的第一个进程本身吗？再往下的一些fork出来的子进程就没办法指定查看了吗？我能否不改变当前大体设计做一些patch work去细化粒度？感谢您的回答，我是安卓方面的新手，感谢赐教

**Comment by JiaHuann** [comment]
所以最细的粒度只能是应用程序的第一个进程本身吗，再往下的一些fork出来的子进程就没办法指定查看了吗？我能否不改变当前大体设计做一些patch work去细化粒度？感谢您的回答，我是安卓方面的新手，感谢赐教。另外，求拉交流群，感谢Author

**Comment by SeeFlowerX** [comment]
uid 0目前已经加入了追踪范围，--uid 0即可，不过最近的改动还没有完成，争取在下个月末前发布正式版本

https://github.com/SeeFlowerX/stackplz/releases/tag/v2.0.0_beta2

**Comment by JiaHuann** [comment]
好的，感谢。如果有额外需求需要assign可以联系，很乐意做一些contribute

**Comment by SeeFlowerX** [comment]
目前最新版已经加入了线程名黑白名单、线程/进程号黑名单功能

以及参数读取等等，新的命令如下：

```
./stackplz -n com.xingin.xhs --point pthread_create[int,pattr*,int,int] -o tmp.log --debug
```

其他新需求会assign，这个issue暂时先关闭了

**Comment by zhang8615050** [comment]
@SeeFlowerX pthread_create 执行上述命令后， 参数不对
<img width="846" alt="image" src="https://github.com/user-attachments/assets/86bfbd71-ff92-4be2-9cab-eaf2654327d9">

**Comment by SeeFlowerX** [comment]
> @SeeFlowerX pthread_create 执行上述命令后， 参数不对 <img alt="image" width="846" src="https://private-user-images.githubusercontent.com/32934132/352970073-86bfbd71-ff92-4be2-9cab-eaf2654327d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTkwMTQsIm5iZiI6MTcyMjI1ODcxNCwicGF0aCI6Ii8zMjkzNDEzMi8zNTI5NzAwNzMtODZiZmJkNzEtZmY5Mi00YmUyLTljYWItZWFmMjY1NDMyN2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEzMTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzOTFlOTk3NWM5NWFhMzk4OTJlZjYwNmRiZmEwZjI1OGI5Yzk4NWI4ZTRhZjFkNDFjM2Y1YWNhODg2NzAyZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fHvRMPsdzUpngAPK5KcU7vjbG3R7--6pRttMgn0JtQQ">

新版本没有这个类型

**Comment by zhang8615050** [comment]
那新版本是什么类型呢？




柴犬小丸子
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SeeFlowerX/stackplz"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月29日(星期一) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SeeFlowerX/stackplz] Report：error:uid is 0, libc.so + pthread_create (Issue #7)





  
@SeeFlowerX pthread_create 执行上述命令后， 参数不对 
  
新版本没有这个类型
