### ISSUE TITLE
Error: unknown flag: --nr

### ISSUE THREAD

**Issue by df13954** [SeeFlowerX/stackplz#9]
使用最新版本的2.0.beta6。
PIxel6，Android13，Linux localhost 5.10.149-android13-4-gebdbc9fbe2e2-dirty #1 SMP PREEMPT Mon Feb 27 10:44:09 UTC 2023 aarch64 Toybox

事例：3.追踪系统调用时的堆栈，以及寄存器信息，支持按pid过滤
```
./stackplz --name com.lemon.lv --pid 11267 syscall --nr 63 --regs --stack
```
尝试测试自己写的demo
```
oriole:/data/local/tmp # ./stackplz-20b6  --name com.debug.cdemo --pid 11419 syscall --nr 63 --regs --stack
Error: unknown flag: --nr
```

**Comment by SeeFlowerX** [comment]
现在改成--syscall了，直接用名字，没有--nr了，看下最近的beta release说明，有命令示意和更新情况

**Comment by df13954** [comment]
ok,感谢
